### ISSUE TITLE
Empty user role name at Permissions page

### ISSUE THREAD

**Issue by pandaskii** [govCMS/GovCMS7#385] opened 2016-11-21 01:01 UTC
![screen shot 2016-11-21 at 11 54 07](https://cloud.githubusercontent.com/assets/1326673/20467705/3da367f2-afe1-11e6-98d1-b33fbea2c8c4.png)

![screen shot 2016-11-21 at 11 57 56](https://cloud.githubusercontent.com/assets/1326673/20467740/c2bceddc-afe1-11e6-95eb-f44a97cc9d75.png)

**Comment by aleayr** [comment] 2017-01-20 04:28
Hi @jozhao 

What role is that (all the standard ones are listed correct, so this looks like a bonus)? Are you proposing we delete it?

**Comment by tobybellwood** [comment] 2017-07-11 09:39
Unable to reproduce - closing

**Closed as completed by tobybellwood** 2017-07-11 09:39 UTC
